### ISSUE TITLE
Random Quote Generator

### ISSUE THREAD

**Issue by surajondev** [surajondev/JavaScript#11]
Create a WebApp that generates random quotes.

You can user API to generate the quote.

**Comment by surajondev** [comment]
Sure. GO ON.

**Comment by surajondev** [comment]
Sure. GO ON.

**Comment by bhushan162** [comment]
can I work on this? and this issue is under hactoberfest ?

**Comment by surajondev** [comment]
Thanks for showing interest in the issue. You can work on it.

**Comment by bhushan162** [comment]
done.
