### ISSUE TITLE
I want  to create a countdown clock 

### ISSUE THREAD

**Issue by DeepakGupta-coder** [surajondev/JavaScript#18]

**Comment by surajondev** [comment]
Thanks for showing interest. You can work on the issue.

**Comment by surajondev** [comment]
You can directly put your directory containing the HTML, CSS an JS files in the root directory.

**Comment by surajondev** [comment]
Whatever you are comfortable with.

**Comment by surajondev** [comment]
It looks dope and works fine. Thanks for the PR.

![image](https://user-images.githubusercontent.com/67496096/193411374-059c52a3-957b-4292-8920-18568dfb94c5.png)
