### ISSUE TITLE
Adding a enhanced UI/UX version for password generator

### ISSUE THREAD

**Issue by HarshallSonawane** [surajondev/JavaScript#182]
Hello sir/ma'am
I am new to this open source world.
It would mean a great deal to me if you allow me to add my project 'Password generator' to this repo and contribute from my end.
I have attached a snapshot as to how it would look.

![image](https://github.com/surajondev/JavaScript/assets/64686104/17dec398-5f33-4709-ab2e-30d31a501e1b)

**Comment by surajondev** [comment]
This looks amazing. You can work on it.

**Comment by HarshallSonawane** [comment]
would this be considered under hacktoberfest label!?

**Comment by surajondev** [comment]
Yess.

**Comment by HarshallSonawane** [comment]
Hello @surajondev !? Any update on the PR
